# Generated by Django 4.1.5 on 2023-08-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_app', '0002_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trans',
            name='t_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Created'),
        ),
    ]
